### PR TITLE
allow multiple usage of seq option

### LINKED ISSUE #168: Unexpected behaviour when using seq option multiple times
The `-1/-i/--seq` option takes the fastq file(s) to be analysed by mykrobe. This option can be used multiple times or just solo. However, I discovered that if it is used multiple times, only the last occurence is used. For example

- `-1 in.fq`: uses `in.fq`
- `-1 in.fq in2.fq`: uses `in.fq` and `in2.fq`
- `-1 in.fq -1 in2.fq`: uses `in2.fq` **only**

### PR DESCRIPTION
**Pull request by mbhall88**
Closes #168 

I have also bumped the version in this PR, so upon merge we can just tag a release.

### CODE REVIEW

**Comment by martinghunt** [comment]
Changes all good. But now we've got all the builds failing for other reasons :(

**Comment by mbhall88** [comment]
> Changes all good. But now we've got all the builds failing for other reasons :(

Story of mykrobe's life 🤣

**Comment by mbhall88** [comment]
Seems to be a `tox` issue. It seems to want `requests`, even if I manually install `requests` before running `tox`.

Not sure why we need `tox` anyway? Seems we only test against one python version anyway? So maybe we just get rid of it and manually call `pytest`?

**Comment by martinghunt** [comment]
Removing tox and using pytest fine with me. Probably reduces the build time as well.

**Comment by mbhall88** [comment]
That's about as much time as I want to spend trying to get the CI to pass. Windows is failing - I think it's something to do with mccortex's bwa?

And just make sure we squash merge this PR so we don't get all the commits from me fiddling with the CI

**Comment by martinghunt** [comment]
Just talked with @iqbal-lab.

Happy to merge and accept that windows build is failing for now on master branch.

But - should we hold off on bumping the version until windows build works again?

**Comment by iqbal-lab** [comment]
I vote no. The challenge of getting windows working consistently is so high, it would delay the new version from beiong available to the many non-windows users. Realistically, it will be a few weeks before we can dedicate the time to get windows working

**Comment by martinghunt** [comment]
ok,  so I'll squash + merge this. Then comment out windows build in a separate PR

**Pull request merged**
