### PR TITLE
 chamila

### PR DESCRIPTION
**Pull request by chamilaadikaram**
[Salmonella.txt](https://github.com/Mykrobe-tools/mykrobe/files/4176482/Salmonella.txt)

### CODE REVIEW

**Comment by iqbal-lab** [comment]
What is this @chamilaadikaram and why do you want to merge it in?

**Comment by iqbal-lab** [comment]
You seen to be trying to add a salmonella plasmid to the repo. I don't think this makes sense, and as it stands we'd need to reject it. Perhaps you can explain what you are trying to achieve?

**Comment by chamilaadikaram** [comment]
I want to use your software. but I cannot find a proper link for that.Please elp me
Chamila Adikaram (PhD)
Specialist (Molecular Microbiology)
Central Public Health LaboratoriesMinistry of HealthOman 
 

    On Sunday, 9 February 2020, 02:15:36 pm GMT+4, Zamin Iqbal <notifications@github.com> wrote:  
 
 
What is this @chamilaadikaram and why do you want to merge it in?

**Comment by mbhall88** [comment]
Hi @chamilaadikaram 

You can find the user manual for Mykrobe [here][docs].  

If these instructions are not clear or you are still unable to achieve the analysis you would like to run then please raise create a [new issue][issues] with an explanation of the problem you are having, and we will be happy to help.  

As a final note, Mykrobe does not provide Salmonella AMR prediction. We currently support *Mycobacterium tuberculosis* and *Staphylococcus aureus*.

[docs]: https://github.com/Mykrobe-tools/mykrobe/wiki
[issues]: https://github.com/Mykrobe-tools/mykrobe/issues

**Comment by chamilaadikaram** [comment]
thank you very much for the reply. Actually my need is analysis of M. tuberculosis. I will go through the manual.

**Comment by chamilaadikaram** [comment]
Hello
thank you for your support. I need to analysis WGS data of M. tuberculosis. I tried to use your web link with know sample data of salmoneela. But I was unable to use it properly. AS you suggested I will go through the manual and try to analysis again
thank you
chamila
Chamila Adikaram (PhD)
Specialist (Molecular Microbiology)
Central Public Health LaboratoriesMinistry of HealthOman 
 

    On Sunday, 9 February 2020, 02:18:17 pm GMT+4, Zamin Iqbal <notifications@github.com> wrote:  
 
 
You seen to be trying to add a salmonella plasmid to the repo. I don't think this makes sense, and as it stands we'd need to reject it. Perhaps you can explain what you are trying to achieve?

**Pull request closed without merging**
