### PR TITLE
Tb lineage update

### PR DESCRIPTION
**Pull request by martinghunt**
Main changes are lineage calling and more flexibility with panel data and adding species. This is in preparation for a new release that will include updated TB lineage calling and adding new species Shigella. I'll update all the documentation in the wiki when the release happens.

* major rewrite of how mykrobe handles panel data. Instead of adding everything from one tarball during install, this is more flexible. Data all live on figshare. Allows adding or updating one species using new `mykrobe panels ...` CLI without needing to update mykrobe itself. Panels live in the same data directory as before by default,  but user can change to put them anywhere.
* Lineage can now be called by defining a lineage tree + associated SNPs, making probes (with a new lineage option), and adding to the panel.
* Tidied up logging output. No longer get all the mccortex stdout/err spamming the terminal. Now you will only see it if there is an error.
* Removed `mykrobe genotype` - same functionality is now available in `mykrobe predict`. Less confusing for the user.

### CODE REVIEW

**Comment by martinghunt** [comment]
Also, would not be surprised if one or both of travis and appveyor fail. I've edited the installs to what I think is correct but we'll have to see. Also possible that they work here, but then fail when we try a release. Can worry about release at the time we make it.

**Comment by martinghunt** [comment]
Linux, mac, and windows automated tests all ok. And the way appveyor works means that it actually runs pyinstaller to make the stand-alone executable. So all looking good.

**Comment by mbhall88** [comment]
This PR is way too big and has too many changes for me to really be able to effectively review it sorry.

One overarching comment I would make is that I think the codebase would be a lot more "understandable" with type annotations. There is heavy use of dictionaries and type annotations help to clarify what data we expect them to contain. And additionally, it is not clear with many functions whether they return anything or not, and if so, what type of variable do they return.

Anyway, feel free to merge if you want.

**Comment by martinghunt** [comment]
Thanks, tagged you in case you wanted to look.

Yep, I agree re typing and I should definitely be doing this more :) One thing with this code base is that it has its own `mykrobe.typing` module and I found having `import typing` was breaking tests depending on how they were run (via pytest/tox/whatever). Using typing will probably mean a bunch more work renaming existing things to stop those errors.

**Pull request merged**
